pipeline {
    agent any

    environment {
        REGION_KWI = credentials("REGION-KWI")
        BUCKET_KWI = credentials("BUCKET-KWI")
        KEY_NAME = "aline-kwi-infra"
    }

    stages {
        stage("Init") {
            steps {
                echo "Initializing Terraform.."
                dir ("terraform/") {
                    sh """
                    terraform init \
                        -backend-config="bucket=${BUCKET_KWI}" \
                        -backend-config="key=${KEY_NAME}" \
                        -backend-config="region=${REGION_KWI}"
                    """
                }
            }
        }

        stage("Plan") {
            steps {
                echo "Creating Terraform Plan"
                dir ("terraform/") {
                    sh "terraform plan -var-file=deployment/input.tfvars -out out/output.tf"
                }
            }
        }

        stage("Apply") {
            steps {
                echo "Applying Terraform Plan"
                dir ("terraform/") {
                    sh "terraform apply -auto-approve -no-color out/output.tf"
                }
            }
        }
    }
}