pipeline {
    agent any

    environment {
        REGION_KWI = credentials("REGION-KWI")
        BUCKET_KWI = credentials("BUCKET-KWI")
        KEY_NAME = "aline-kwi-infra"
        DEPLOY_DIR = "terraform/deployment"
        AWS_PROFILE = "keshaun"
    }

    stages {
        stage("Init") {
            steps {
                echo "Initializing Terraform.."
                dir ("${DEPLOY_DIR}") {
                    sh """
                    terraform init \
                        -no-color \
                        -backend-config="bucket=${BUCKET_KWI}" \
                        -backend-config="key=${KEY_NAME}" \
                        -backend-config="region=${REGION_KWI}"
                    """
                }
            }
        }

        stage("Plan") {
            steps {
                echo "Creating Terraform Plan"
                dir ("${DEPLOY_DIR}") {
                    sh "terraform plan -var-file=input.tfvars -no-color -out out.tf"
                }
            }
        }

        stage("Apply") {
            steps {
                echo "Applying Terraform Plan"
                dir ("${DEPLOY_DIR}") {
                    sh "terraform apply -auto-approve -no-color out.tf"
                }
            }
        }
    }

    post {
        always {
            sh "rm ${DEPLOY_DIR}/out.tf"
        }
    }
}