apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::086620157175:user/ricky.lopez
      username: ricky.lopez
      groups:
        - eks-console-dashboard-full-access-group
