apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: 086620157175.dkr.ecr.us-east-1.amazonaws.com/gateway-kwi
        
        ports:
        - containerPort: 8080
        env:
          - name: APP_PORT
            value: "8080"
        envFrom:
          - configMapRef:
              name: env
          - secretRef:
              name: secret
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30000