apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: aline
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: keshaunw/gateway
        ports:
        - containerPort: 8080
        env:
          - name: APP_PORT
            value: "8080"
          - name: APP_SERVICE_HOST
            valueFrom:
              configMapKeyRef:
                key: APP_SERVICE_HOST
                name: env
          - name: PORTAL_ADMIN
            valueFrom:
              configMapKeyRef:
                key: PORTAL_ADMIN
                name: env
          - name: PORTAL_DASHBOARD
            valueFrom:
              configMapKeyRef:
                key: PORTAL_DASHBOARD
                name: env
          - name: PORTAL_LANDING
            valueFrom:
              configMapKeyRef:
                key: PORTAL_LANDING
                name: env
        envFrom:
          - configMapRef:
              name: env
          - secretRef:
              name: secret
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: aline
spec:
  selector:
    app: gateway
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30000