apiVersion: apps/v1
kind: Deployment
metadata:
  name: underwriter-deployment
  labels:
    app: underwriter
    role: microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: underwriter
  template:
    metadata:
      labels:
        app: underwriter
        role: microservice
    spec:
      containers:
      - name: underwriter
        image: 086620157175.dkr.ecr.us-east-1.amazonaws.com/underwriter-microservice-kwi
        ports:
        - name: underwriter
          containerPort: 8071
        env:
          - name: APP_PORT
            value: "8071"
        envFrom:
          - configMapRef:
              name: env
          - secretRef:
              name: secret