apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user
    role: microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: keshaunw/user-microservice
        ports:
        - containerPort: 8070
        env:
          - name: APP_PORT
            value: "8070"
        envFrom:
          - configMapRef:
              name: env
          - secretRef:
              name: secret
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user
  type: NodePort
  ports:
  - protocol: TCP
    port: 8070
    targetPort: 8070
    nodePort: 30001